//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.11 at 07:05:06 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.silver.com/springbootsoapdemo/loanEligibility", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.silver.springbootsoapdemo.loaneligibility;
